export PYTHONPATH="${PYTHONPATH}:/p/home/jusers/finkbeiner1/jureca/util/tonic_fork"

POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/shd_numIpus1_nnpt2_numHidLayers3_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=3 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=48 --dataset_name=SHD --num_neurons_per_tile=2 --ipu_id=-1 --num_ipus=1
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/nmnist_numIpus1_nnpt2_numHidLayers3_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=3 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=32 --dataset_name=NMNIST --num_neurons_per_tile=2 --ipu_id=-1 --num_ipus=1
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/shd_numIpus1_nnpt4_numHidLayers6_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=6 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=48 --dataset_name=SHD --num_neurons_per_tile=4 --ipu_id=-1 --num_ipus=1
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/nmnist_numIpus1_nnpt4_numHidLayers6_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=6 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=32 --dataset_name=NMNIST --num_neurons_per_tile=4 --ipu_id=-1 --num_ipus=1
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/shd_numIpus2_nnpt2_numHidLayers3_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=3 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=48 --dataset_name=SHD --num_neurons_per_tile=2 --ipu_id=-1 --num_ipus=2
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/nmnist_numIpus2_nnpt2_numHidLayers3_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=3 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=32 --dataset_name=NMNIST --num_neurons_per_tile=2 --ipu_id=-1 --num_ipus=2
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/shd_numIpus4_nnpt2_numHidLayers3_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=3 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=48 --dataset_name=SHD --num_neurons_per_tile=2 --ipu_id=-1 --num_ipus=4
POPLAR_ENGINE_OPTIONS='{"autoReport.all":"true", "autoReport.directory":"./reports_final/nmnist_numIpus4_nnpt2_numHidLayers3_zeroAct", "autoReport.executionProfileProgramRunCount":"2"}' python3 benchmarking_script.py --use_ipu=1 --impl_method=sparse_layer --profile_run=1 --max_activity=0.05 --batchsize=24 --lr=0.00005 --transpose_weights=1 --second_thresh=0.9 --num_hidden_layers=3 --bench_mode=multi_neuron --weight_mul=2.0 --sparse_size_inp=32 --dataset_name=NMNIST --num_neurons_per_tile=2 --ipu_id=-1 --num_ipus=4
